<?php

use Illuminate\Database\Seeder;

class ProActivityTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('pro_activity')->delete();
        $date = date("Y-m-d");
        $date = strtotime("-17 day",strtotime($date));
        // $date = strtotime($date);
        \DB::table('pro_activity')->insert(array (
            0 => 
            array (
                'id' => 1,
                'code' => 'ACT192040001',
                'name' => 'Plate',
                'description' => 'Plate',
                'status' => 1,
                'wbs_id' => 7,
                'activity_configuration_id' => 186,
                'planned_duration' => 6,
                'planned_start_date' => date("Y-m-d",strtotime("+4 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+9 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => date("Y-m-d",strtotime("+4 day", $date)),
                'actual_end_date' => NULL,
                'progress' => 50.0,
                'weight' => 12.0,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            1 => 
            array (
                'id' => 3,
                'code' => 'ACT192040002',
                'name' => 'Stiffener Line 1-5',
                'description' => 'Stiffener Line 1-5',
                'status' => 1,
                'wbs_id' => 7,
                'activity_configuration_id' => 187,
                'planned_duration' => 5,
                'planned_start_date' => date("Y-m-d",strtotime("+9 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+13 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 11.0,
                'predecessor' => '[[1,"fs"]]',
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            2 => 
            array (
                'id' => 4,
                'code' => 'ACT192040003',
                'name' => 'Roundbar',
                'description' => 'Roundbar',
                'status' => 1,
                'wbs_id' => 7,
                'activity_configuration_id' => 188,
                'planned_duration' => 5,
                'planned_start_date' => date("Y-m-d",strtotime("+13 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+17 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 12.0,
                'predecessor' => '[[3,"fs"]]',
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            3 => 
            array (
                'id' => 5,
                'code' => 'ACT192040004',
                'name' => 'Plate',
                'description' => 'Plate',
                'status' => 1,
                'wbs_id' => 12,
                'activity_configuration_id' => 192,
                'planned_duration' => 4,
                'planned_start_date' => date("Y-m-d",strtotime("+18 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+21 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 4.5,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            4 => 
            array (
                'id' => 6,
                'code' => 'ACT192040005',
                'name' => 'Strip',
                'description' => 'Strip',
                'status' => 1,
                'wbs_id' => 12,
                'activity_configuration_id' => 193,
                'planned_duration' => 2,
                'planned_start_date' => date("Y-m-d",strtotime("+21 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+22 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 6.5,
                'predecessor' => '[[5,"fs"]]',
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            5 => 
            array (
                'id' => 7,
                'code' => 'ACT192040006',
                'name' => 'Engsel',
                'description' => 'Engsel',
                'status' => 1,
                'wbs_id' => 12,
                'activity_configuration_id' => 194,
                'planned_duration' => 3,
                'planned_start_date' => date("Y-m-d",strtotime("+22 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+24 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 6.5,
                'predecessor' => '[[6,"fs"]]',
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            6 => 
            array (
                'id' => 8,
                'code' => 'ACT192040007',
                'name' => 'Plate',
                'description' => 'Plate',
                'status' => 1,
                'wbs_id' => 10,
                'activity_configuration_id' => 195,
                'planned_duration' => 2,
                'planned_start_date' => date("Y-m-d",strtotime("+25 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+26 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 4.5,
                'predecessor' => '[[7,"fs"]]',
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            7 => 
            array (
                'id' => 9,
                'code' => 'ACT192040008',
                'name' => 'Strip',
                'description' => 'Strip',
                'status' => 1,
                'wbs_id' => 10,
                'activity_configuration_id' => 196,
                'planned_duration' => 4,
                'planned_start_date' => date("Y-m-d",strtotime("+26 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+29 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 6.5,
                'predecessor' => '[[8,"fs"]]',
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            8 => 
            array (
                'id' => 10,
                'code' => 'ACT192040009',
                'name' => 'Engsel',
                'description' => 'Engsel',
                'status' => 1,
                'wbs_id' => 10,
                'activity_configuration_id' => 197,
                'planned_duration' => 3,
                'planned_start_date' => date("Y-m-d",strtotime("+29 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+31 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 6.5,
                'predecessor' => '[[9,"fs"]]',
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            9 => 
            array (
                'id' => 11,
                'code' => 'ACT192040010',
                'name' => 'Persiapan pengedokan
',
                'description' => 'Persiapan pengedokan
',
                'status' => 0,
                'wbs_id' => 1,
                'activity_configuration_id' => 171,
                'planned_duration' => 1,
                'planned_start_date' => date("Y-m-d",strtotime("+1 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+1 day", $date)),
                'actual_duration' => 1,
                'actual_start_date' => date("Y-m-d",strtotime("+1 day", $date)),
                'actual_end_date' => date("Y-m-d",strtotime("+1 day", $date)),
                'progress' => 100.0,
                'weight' => 2.5,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            10 => 
            array (
                'id' => 12,
                'code' => 'ACT192040011',
                'name' => 'Docking',
                'description' => 'Docking',
                'status' => 0,
                'wbs_id' => 1,
                'activity_configuration_id' => 172,
                'planned_duration' => 1,
                'planned_start_date' => date("Y-m-d",strtotime("+2 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+2 day", $date)),
                'actual_duration' => 1,
                'actual_start_date' => date("Y-m-d",strtotime("+2 day", $date)),
                'actual_end_date' => date("Y-m-d",strtotime("+2 day", $date)),
                'progress' => 100.0,
                'weight' => 5.0,
                'predecessor' => '[[11,"fs"]]',
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            11 => 
            array (
                'id' => 13,
                'code' => 'ACT192040012',
                'name' => 'Gambar Bukaan Kulit',
                'description' => 'Gambar Bukaan Kulit',
                'status' => 0,
                'wbs_id' => 1,
                'activity_configuration_id' => 199,
                'planned_duration' => 1,
                'planned_start_date' => date("Y-m-d",strtotime("+3 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+3 day", $date)),
                'actual_duration' => 1,
                'actual_start_date' => date("Y-m-d",strtotime("+3 day", $date)),
                'actual_end_date' => date("Y-m-d",strtotime("+3 day", $date)),
                'progress' => 100.0,
                'weight' => 5.0,
                'predecessor' => '[[12,"fs"]]',
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            12 => 
            array (
                'id' => 15,
                'code' => 'ACT192040013',
                'name' => 'Undocking',
                'description' => 'Undocking',
                'status' => 1,
                'wbs_id' => 11,
                'activity_configuration_id' => 198,
                'planned_duration' => 1,
                'planned_start_date' => date("Y-m-d",strtotime("+32 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+32 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 5.0,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            13 => 
            array (
                'id' => 16,
                'code' => 'ACT192040014',
                'name' => 'Air Pressure Test pada tangki void area perbaikan
',
                'description' => 'Air Pressure Test pada tangki void area perbaikan
',
                'status' => 1,
                'wbs_id' => 2,
                'activity_configuration_id' => 184,
                'planned_duration' => 1,
                'planned_start_date' => date("Y-m-d",strtotime("+32 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+32 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 6.0,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            14 => 
            array (
                'id' => 17,
                'code' => 'ACT192040015',
                'name' => 'Pembuatan laporan hasil pekerjaan dan dokumen lainnya
',
                'description' => 'Pembuatan laporan hasil pekerjaan dan dokumen lainnya
',
                'status' => 1,
                'wbs_id' => 2,
                'activity_configuration_id' => 182,
                'planned_duration' => 6,
                'planned_start_date' => date("Y-m-d",strtotime("+32 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+37 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 6.5,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
        ));
        

        $date = date("Y-m-d");
        $date = strtotime($date);
        \DB::table('pro_activity')->insert(array (
            0 => 
            array (
                'id' => 18,
                'code' => 'ACT192050001',
                'name' => 'Plate',
                'description' => 'Plate',
                'status' => 0,
                'wbs_id' => 22,
                'activity_configuration_id' => 186,
                'planned_duration' => 6,
                'planned_start_date' => date("Y-m-d",strtotime("+4 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+9 day", $date)),
                'actual_duration' => 5,
                'actual_start_date' => date("Y-m-d",strtotime("+4 day", $date)),
                'actual_end_date' => date("Y-m-d",strtotime("+8 day", $date)),
                'progress' => 100.0,
                'weight' => 12.0,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            1 => 
            array (
                'id' => 19,
                'code' => 'ACT192050002',
                'name' => 'Stiffener Line 1-5',
                'description' => 'Stiffener Line 1-5',
                'status' => 0,
                'wbs_id' => 22,
                'activity_configuration_id' => 187,
                'planned_duration' => 5,
                'planned_start_date' => date("Y-m-d",strtotime("+9 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+13 day", $date)),
                'actual_duration' => 5,
                'actual_start_date' => date("Y-m-d",strtotime("+8 day", $date)),
                'actual_end_date' => date("Y-m-d",strtotime("+12 day", $date)),
                'progress' => 100.0,
                'weight' => 11.0,
                'predecessor' => '[[18,"fs"]]',
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            2 => 
            array (
                'id' => 20,
                'code' => 'ACT192050003',
                'name' => 'Roundbar',
                'description' => 'Roundbar',
                'status' => 0,
                'wbs_id' => 22,
                'activity_configuration_id' => 188,
                'planned_duration' => 5,
                'planned_start_date' => date("Y-m-d",strtotime("+13 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+17 day", $date)),
                'actual_duration' => 3,
                'actual_start_date' => date("Y-m-d",strtotime("+12 day", $date)),
                'actual_end_date' => date("Y-m-d",strtotime("+14 day", $date)),
                'progress' => 100.0,
                'weight' => 12.0,
                'predecessor' => '[[19,"fs"]]',
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            3 => 
            array (
                'id' => 21,
                'code' => 'ACT192050004',
                'name' => 'Plate',
                'description' => 'Plate',
                'status' => 0,
                'wbs_id' => 27,
                'activity_configuration_id' => 192,
                'planned_duration' => 4,
                'planned_start_date' => date("Y-m-d",strtotime("+18 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+21 day", $date)),
                'actual_duration' => 4,
                'actual_start_date' => date("Y-m-d",strtotime("+18 day", $date)),
                'actual_end_date' => date("Y-m-d",strtotime("+21 day", $date)),
                'progress' => 100.0,
                'weight' => 4.5,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            4 => 
            array (
                'id' => 22,
                'code' => 'ACT192050005',
                'name' => 'Strip',
                'description' => 'Strip',
                'status' => 0,
                'wbs_id' => 27,
                'activity_configuration_id' => 193,
                'planned_duration' => 2,
                'planned_start_date' => date("Y-m-d",strtotime("+21 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+22 day", $date)),
                'actual_duration' => 4,
                'actual_start_date' => date("Y-m-d",strtotime("+21 day", $date)),
                'actual_end_date' => date("Y-m-d",strtotime("+24 day", $date)),
                'progress' => 100.0,
                'weight' => 6.5,
                'predecessor' => '[[21,"fs"]]',
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            5 => 
            array (
                'id' => 23,
                'code' => 'ACT192050006',
                'name' => 'Engsel',
                'description' => 'Engsel',
                'status' => 0,
                'wbs_id' => 27,
                'activity_configuration_id' => 194,
                'planned_duration' => 3,
                'planned_start_date' => date("Y-m-d",strtotime("+22 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+24 day", $date)),
                'actual_duration' => 2,
                'actual_start_date' => date("Y-m-d",strtotime("+22 day", $date)),
                'actual_end_date' => date("Y-m-d",strtotime("+23 day", $date)),
                'progress' => 100.0,
                'weight' => 6.5,
                'predecessor' => '[[22,"fs"]]',
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            6 => 
            array (
                'id' => 24,
                'code' => 'ACT192050007',
                'name' => 'Plate',
                'description' => 'Plate',
                'status' => 0,
                'wbs_id' => 25,
                'activity_configuration_id' => 195,
                'planned_duration' => 2,
                'planned_start_date' => date("Y-m-d",strtotime("+25 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+26 day", $date)),
                'actual_duration' => 2,
                'actual_start_date' => date("Y-m-d",strtotime("+25 day", $date)),
                'actual_end_date' => date("Y-m-d",strtotime("+26 day", $date)),
                'progress' => 100.0,
                'weight' => 4.5,
                'predecessor' => '[[23,"fs"]]',
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            7 => 
            array (
                'id' => 25,
                'code' => 'ACT192050008',
                'name' => 'Strip',
                'description' => 'Strip',
                'status' => 0,
                'wbs_id' => 25,
                'activity_configuration_id' => 196,
                'planned_duration' => 4,
                'planned_start_date' => date("Y-m-d",strtotime("+26 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+29 day", $date)),
                'actual_duration' => 6,
                'actual_start_date' => date("Y-m-d",strtotime("+26 day", $date)),
                'actual_end_date' => date("Y-m-d",strtotime("+31 day", $date)),
                'progress' => 100.0,
                'weight' => 6.5,
                'predecessor' => '[[24,"fs"]]',
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            8 => 
            array (
                'id' => 26,
                'code' => 'ACT192050009',
                'name' => 'Engsel',
                'description' => 'Engsel',
                'status' => 0,
                'wbs_id' => 25,
                'activity_configuration_id' => 197,
                'planned_duration' => 3,
                'planned_start_date' => date("Y-m-d",strtotime("+29 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+31 day", $date)),
                'actual_duration' => 3,
                'actual_start_date' => date("Y-m-d",strtotime("+31 day", $date)),
                'actual_end_date' => date("Y-m-d",strtotime("+33 day", $date)),
                'progress' => 100.0,
                'weight' => 6.5,
                'predecessor' => '[[25,"fs"]]',
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            9 => 
            array (
                'id' => 27,
                'code' => 'ACT192050010',
                'name' => 'Persiapan pengedokan
',
                'description' => 'Persiapan pengedokan
',
                'status' => 0,
                'wbs_id' => 16,
                'activity_configuration_id' => 171,
                'planned_duration' => 1,
                'planned_start_date' => date("Y-m-d",strtotime("+1 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+1 day", $date)),
                'actual_duration' => 1,
                'actual_start_date' => date("Y-m-d",strtotime("+1 day", $date)),
                'actual_end_date' => date("Y-m-d",strtotime("+1 day", $date)),
                'progress' => 100.0,
                'weight' => 2.5,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            10 => 
            array (
                'id' => 28,
                'code' => 'ACT192050011',
                'name' => 'Docking',
                'description' => 'Docking',
                'status' => 0,
                'wbs_id' => 16,
                'activity_configuration_id' => 172,
                'planned_duration' => 1,
                'planned_start_date' => date("Y-m-d",strtotime("+2 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+2 day", $date)),
                'actual_duration' => 1,
                'actual_start_date' => date("Y-m-d",strtotime("+2 day", $date)),
                'actual_end_date' => date("Y-m-d",strtotime("+2 day", $date)),
                'progress' => 100.0,
                'weight' => 5.0,
                'predecessor' => '[[27,"fs"]]',
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            11 => 
            array (
                'id' => 29,
                'code' => 'ACT192050012',
                'name' => 'Gambar Bukaan Kulit',
                'description' => 'Gambar Bukaan Kulit',
                'status' => 0,
                'wbs_id' => 16,
                'activity_configuration_id' => 199,
                'planned_duration' => 1,
                'planned_start_date' => date("Y-m-d",strtotime("+3 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+3 day", $date)),
                'actual_duration' => 2,
                'actual_start_date' => date("Y-m-d",strtotime("+3 day", $date)),
                'actual_end_date' => date("Y-m-d",strtotime("+4 day", $date)),
                'progress' => 100,
                'weight' => 5.0,
                'predecessor' => '[[28,"fs"]]',
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            12 => 
            array (
                'id' => 30,
                'code' => 'ACT192050013',
                'name' => 'Undocking',
                'description' => 'Undocking',
                'status' => 0,
                'wbs_id' => 26,
                'activity_configuration_id' => 198,
                'planned_duration' => 1,
                'planned_start_date' => date("Y-m-d",strtotime("+32 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+32 day", $date)),
                'actual_duration' => 1,
                'actual_start_date' => date("Y-m-d",strtotime("+32 day", $date)),
                'actual_end_date' => date("Y-m-d",strtotime("+32 day", $date)),
                'progress' => 100.0,
                'weight' => 5.0,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            13 => 
            array (
                'id' => 31,
                'code' => 'ACT192050014',
                'name' => 'Air Pressure Test pada tangki void area perbaikan
',
                'description' => 'Air Pressure Test pada tangki void area perbaikan
',
                'status' => 0,
                'wbs_id' => 17,
                'activity_configuration_id' => 184,
                'planned_duration' => 1,
                'planned_start_date' => date("Y-m-d",strtotime("+32 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+32 day", $date)),
                'actual_duration' => 1,
                'actual_start_date' => date("Y-m-d",strtotime("+32 day", $date)),
                'actual_end_date' => date("Y-m-d",strtotime("+32 day", $date)),
                'progress' => 100.0,
                'weight' => 6.0,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            14 => 
            array (
                'id' => 32,
                'code' => 'ACT192050015',
                'name' => 'Pembuatan laporan hasil pekerjaan dan dokumen lainnya
',
                'description' => 'Pembuatan laporan hasil pekerjaan dan dokumen lainnya
',
                'status' => 0,
                'wbs_id' => 17,
                'activity_configuration_id' => 182,
                'planned_duration' => 6,
                'planned_start_date' => date("Y-m-d",strtotime("+32 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+37 day", $date)),
                'actual_duration' => 6,
                'actual_start_date' => date("Y-m-d",strtotime("+32 day", $date)),
                'actual_end_date' => date("Y-m-d",strtotime("+37 day", $date)),
                'progress' => 100.0,
                'weight' => 6.5,
                'predecessor' => NULL,
                'user_id' => 3,
                'branch_id' => 2,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
        ));
        
    }
}