<?php

use Illuminate\Database\Seeder;

class ProWbsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('pro_wbs')->delete();
        
        $date = date("Y-m-d");
        // $date = strtotime($date);
        $date = strtotime("-17 day",strtotime($date));

        \DB::table('pro_wbs')->insert(array (
            0 => 
            array (
                'id' => 1,
                'code' => 'WBS192050001',
                'number' => 'Docking',
                'description' => 'Docking (Pengedokan)',
                'deliverables' => 'Docking/Undocking',
                'project_id' => 5,
                'wbs_id' => NULL,
                'wbs_configuration_id' => 1,
                'status' => 0,
                'planned_duration' => 3,
                'planned_start_date' => date("Y-m-d",strtotime("+1 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+3 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 100.0,
                'weight' => 12.5,
                'user_id' => 3,
                'branch_id' => 2,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            1 => 
            array (
                'id' => 2,
                'code' => 'WBS192050002',
                'number' => 'General Services',
                'description' => 'General Services (Pelayanan Umum)',
                'deliverables' => 'General Services',
                'project_id' => 5,
                'wbs_id' => NULL,
                'wbs_configuration_id' => 2,
                'status' => 1,
                'planned_duration' => 6,
                'planned_start_date' => date("Y-m-d",strtotime("+32 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+37 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 12.5,
                'user_id' => 3,
                'branch_id' => 2,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            2 => 
            array (
                'id' => 3,
                'code' => 'WBS192050003',
                'number' => 'Working',
                'description' => 'Working ',
                'deliverables' => 'Working ',
                'project_id' => 5,
                'wbs_id' => NULL,
                'wbs_configuration_id' => 3,
                'status' => 1,
                'planned_duration' => 28,
                'planned_start_date' => date("Y-m-d",strtotime("+4 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+31 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 70.0,
                'user_id' => 3,
                'branch_id' => 2,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            3 => 
            array (
                'id' => 4,
                'code' => 'WBS192050004',
                'number' => 'Replating',
                'description' => 'Penggantian Plat (Replating)',
                'deliverables' => 'Replating',
                'project_id' => 5,
                'wbs_id' => 3,
                'wbs_configuration_id' => 5,
                'status' => 1,
                'planned_duration' => 14,
                'planned_start_date' => date("Y-m-d",strtotime("+4 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+17 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 35.0,
                'user_id' => 3,
                'branch_id' => 2,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            4 => 
            array (
                'id' => 5,
                'code' => 'WBS192050005',
                'number' => 'Out Fitting',
                'description' => 'Out Fitting',
                'deliverables' => 'Out Fitting',
                'project_id' => 5,
                'wbs_id' => 3,
                'wbs_configuration_id' => 68,
                'status' => 1,
                'planned_duration' => 14,
                'planned_start_date' => date("Y-m-d",strtotime("+18 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+31 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 35.0,
                'user_id' => 3,
                'branch_id' => 2,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            5 => 
            array (
                'id' => 6,
                'code' => 'WBS192050006',
                'number' => 'Sideboard Forward',
                'description' => 'Sideboard Forward',
                'deliverables' => 'Sideboard Forward',
                'project_id' => 5,
                'wbs_id' => 4,
                'wbs_configuration_id' => 6,
                'status' => 1,
                'planned_duration' => 14,
                'planned_start_date' => date("Y-m-d",strtotime("+4 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+17 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 35.0,
                'user_id' => 3,
                'branch_id' => 2,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            6 => 
            array (
                'id' => 7,
                'code' => 'WBS192050007',
                'number' => 'Panel Block F1',
                'description' => 'Panel Block F1',
                'deliverables' => 'Panel Block F1',
                'project_id' => 5,
                'wbs_id' => 6,
                'wbs_configuration_id' => 85,
                'status' => 1,
                'planned_duration' => 14,
                'planned_start_date' => date("Y-m-d",strtotime("+4 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+17 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 35.0,
                'user_id' => 3,
                'branch_id' => 2,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            7 => 
            array (
                'id' => 8,
                'code' => 'WBS192050008',
                'number' => 'Winch House',
                'description' => 'Winch House',
                'deliverables' => 'Winch House',
                'project_id' => 5,
                'wbs_id' => 5,
                'wbs_configuration_id' => 87,
                'status' => 1,
                'planned_duration' => 14,
                'planned_start_date' => date("Y-m-d",strtotime("+18 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+31 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 35.0,
                'user_id' => 3,
                'branch_id' => 2,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            8 => 
            array (
                'id' => 9,
                'code' => 'WBS192050009',
                'number' => 'Pembuatan 2 Pintu Besar',
                'description' => 'Pembuatan 2 Pintu Besar',
                'deliverables' => 'Pembuatan 2 Pintu Besar',
                'project_id' => 5,
                'wbs_id' => 8,
                'wbs_configuration_id' => 88,
                'status' => 1,
                'planned_duration' => 14,
                'planned_start_date' => date("Y-m-d",strtotime("+18 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+31 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 17.5,
                'user_id' => 3,
                'branch_id' => 2,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            9 => 
            array (
                'id' => 10,
                'code' => 'WBS192050010',
                'number' => 'Pintu Sekat',
                'description' => 'Pintu Sekat',
                'deliverables' => 'Pintu Sekat',
                'project_id' => 5,
                'wbs_id' => 9,
                'wbs_configuration_id' => 91,
                'status' => 1,
                'planned_duration' => 7,
                'planned_start_date' => date("Y-m-d",strtotime("+25 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+31 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 17.5,
                'user_id' => 3,
                'branch_id' => 2,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            10 => 
            array (
                'id' => 11,
                'code' => 'WBS192050011',
                'number' => 'Undocking',
            'description' => 'Undocking',
                'deliverables' => 'Docking/Undocking',
                'project_id' => 5,
                'wbs_id' => NULL,
                'wbs_configuration_id' => 1,
                'status' => 1,
                'planned_duration' => 1,
                'planned_start_date' => date("Y-m-d",strtotime("+32 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+32 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 5.0,
                'user_id' => 3,
                'branch_id' => 2,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            11 => 
            array (
                'id' => 12,
                'code' => 'WBS192050012',
                'number' => 'Pintu Forward',
                'description' => 'Pintu Forward',
                'deliverables' => 'Pintu Forward',
                'project_id' => 5,
                'wbs_id' => 9,
                'wbs_configuration_id' => 90,
                'status' => 1,
                'planned_duration' => 7,
                'planned_start_date' => date("Y-m-d",strtotime("+18 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+24 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 17.5,
                'user_id' => 3,
                'branch_id' => 2,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
        ));


        $date = date("Y-m-d");
        $date = strtotime("-16 day",strtotime($date));

        \DB::table('pro_wbs')->insert(array (
            0 => 
            array (
                'id' => 13,
                'code' => 'WBS192020001',
                'number' => 'Docking',
                'description' => 'Docking (Pengedokan)',
                'deliverables' => 'Docking/Undocking',
                'project_id' => 2,
                'wbs_id' => NULL,
                'wbs_configuration_id' => 1,
                'status' => 1,
                'planned_duration' => 9,
                'planned_start_date' => date("Y-m-d",strtotime("+1 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+9 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 50.0,
                'user_id' => 3,
                'branch_id' => 2,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            1 => 
            array (
                'id' => 14,
                'code' => 'WBS192020002',
                'number' => 'Working',
                'description' => 'Working ',
                'deliverables' => 'Working ',
                'project_id' => 2,
                'wbs_id' => NULL,
                'wbs_configuration_id' => 3,
                'status' => 1,
                'planned_duration' => 17,
                'planned_start_date' => date("Y-m-d",strtotime("+11 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+27 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 50.0,
                'user_id' => 3,
                'branch_id' => 2,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
        ));
        $date = date("Y-m-d");
        $date = strtotime("-20 day",strtotime($date));
        \DB::table('pro_wbs')->insert(array (
            0 => 
            array (
                'id' => 15,
                'code' => 'WBS192030001',
                'number' => 'Docking',
                'description' => 'Docking (Pengedokan)',
                'deliverables' => 'Docking/Undocking',
                'project_id' => 3,
                'wbs_id' => NULL,
                'wbs_configuration_id' => 1,
                'status' => 1,
                'planned_duration' => 11,
                'planned_start_date' => date("Y-m-d",strtotime("+1 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+11 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 0.0,
                'weight' => 100.0,
                'user_id' => 3,
                'branch_id' => 2,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
        ));
        
        $date = date("Y-m-d");
        $date = strtotime($date);

        \DB::table('pro_wbs')->insert(array (
            0 => 
            array (
                'id' => 16,
                'code' => 'WBS192060001',
                'number' => 'Docking',
            'description' => 'Docking (Pengedokan)',
                'deliverables' => 'Docking/Undocking',
                'project_id' => 6,
                'wbs_id' => NULL,
                'wbs_configuration_id' => 1,
                'status' => 1,
                'planned_duration' => 3,
                'planned_start_date' => date("Y-m-d",strtotime("+1 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+3 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 100.0,
                'weight' => 12.5,
                'user_id' => 3,
                'branch_id' => 2,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            1 => 
            array (
                'id' => 17,
                'code' => 'WBS192060002',
                'number' => 'General Services',
            'description' => 'General Services (Pelayanan Umum)',
                'deliverables' => 'General Services',
                'project_id' => 6,
                'wbs_id' => NULL,
                'wbs_configuration_id' => 2,
                'status' => 1,
                'planned_duration' => 6,
                'planned_start_date' => date("Y-m-d",strtotime("+32 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+37 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 100.0,
                'weight' => 12.5,
                'user_id' => 3,
                'branch_id' => 2,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            2 => 
            array (
                'id' => 18,
                'code' => 'WBS192060003',
                'number' => 'Working',
                'description' => 'Working ',
                'deliverables' => 'Working ',
                'project_id' => 6,
                'wbs_id' => NULL,
                'wbs_configuration_id' => 3,
                'status' => 1,
                'planned_duration' => 28,
                'planned_start_date' => date("Y-m-d",strtotime("+4 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+31 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 100.0,
                'weight' => 70.0,
                'user_id' => 3,
                'branch_id' => 2,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            3 => 
            array (
                'id' => 19,
                'code' => 'WBS192060004',
                'number' => 'Replating',
            'description' => 'Penggantian Plat (Replating)',
                'deliverables' => 'Replating',
                'project_id' => 6,
                'wbs_id' => 18,
                'wbs_configuration_id' => 5,
                'status' => 1,
                'planned_duration' => 14,
                'planned_start_date' => date("Y-m-d",strtotime("+4 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+17 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 100.0,
                'weight' => 35.0,
                'user_id' => 3,
                'branch_id' => 2,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            4 => 
            array (
                'id' => 20,
                'code' => 'WBS192060005',
                'number' => 'Out Fitting',
                'description' => 'Out Fitting',
                'deliverables' => 'Out Fitting',
                'project_id' => 6,
                'wbs_id' => 18,
                'wbs_configuration_id' => 68,
                'status' => 1,
                'planned_duration' => 14,
                'planned_start_date' => date("Y-m-d",strtotime("+18 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+31 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 100.0,
                'weight' => 35.0,
                'user_id' => 3,
                'branch_id' => 2,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            5 => 
            array (
                'id' => 21,
                'code' => 'WBS192060006',
                'number' => 'Sideboard Forward',
                'description' => 'Sideboard Forward',
                'deliverables' => 'Sideboard Forward',
                'project_id' => 6,
                'wbs_id' => 19,
                'wbs_configuration_id' => 6,
                'status' => 1,
                'planned_duration' => 14,
                'planned_start_date' => date("Y-m-d",strtotime("+4 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+17 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 100.0,
                'weight' => 35.0,
                'user_id' => 3,
                'branch_id' => 2,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            6 => 
            array (
                'id' => 22,
                'code' => 'WBS192060007',
                'number' => 'Panel Block F1',
                'description' => 'Panel Block F1',
                'deliverables' => 'Panel Block F1',
                'project_id' => 6,
                'wbs_id' => 21,
                'wbs_configuration_id' => 85,
                'status' => 1,
                'planned_duration' => 14,
                'planned_start_date' => date("Y-m-d",strtotime("+4 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+17 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 100.0,
                'weight' => 35.0,
                'user_id' => 3,
                'branch_id' => 2,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            7 => 
            array (
                'id' => 23,
                'code' => 'WBS192060008',
                'number' => 'Winch House',
                'description' => 'Winch House',
                'deliverables' => 'Winch House',
                'project_id' => 6,
                'wbs_id' => 20,
                'wbs_configuration_id' => 87,
                'status' => 1,
                'planned_duration' => 14,
                'planned_start_date' => date("Y-m-d",strtotime("+18 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+31 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 100.0,
                'weight' => 35.0,
                'user_id' => 3,
                'branch_id' => 2,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            8 => 
            array (
                'id' => 24,
                'code' => 'WBS192060009',
                'number' => 'Pembuatan 2 Pintu Besar',
                'description' => 'Pembuatan 2 Pintu Besar',
                'deliverables' => 'Pembuatan 2 Pintu Besar',
                'project_id' => 6,
                'wbs_id' => 23,
                'wbs_configuration_id' => 88,
                'status' => 1,
                'planned_duration' => 14,
                'planned_start_date' => date("Y-m-d",strtotime("+18 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+31 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 100.0,
                'weight' => 35,
                'user_id' => 3,
                'branch_id' => 2,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            9 => 
            array (
                'id' => 25,
                'code' => 'WBS192060010',
                'number' => 'Pintu Sekat',
                'description' => 'Pintu Sekat',
                'deliverables' => 'Pintu Sekat',
                'project_id' => 6,
                'wbs_id' => 24,
                'wbs_configuration_id' => 91,
                'status' => 1,
                'planned_duration' => 7,
                'planned_start_date' => date("Y-m-d",strtotime("+25 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+31 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 100.0,
                'weight' => 17.5,
                'user_id' => 3,
                'branch_id' => 2,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            10 => 
            array (
                'id' => 26,
                'code' => 'WBS192060011',
                'number' => 'Undocking',
                'description' => 'Undocking',
                'deliverables' => 'Docking/Undocking',
                'project_id' => 6,
                'wbs_id' => NULL,
                'wbs_configuration_id' => 1,
                'status' => 1,
                'planned_duration' => 1,
                'planned_start_date' => date("Y-m-d",strtotime("+32 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+32 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 100.0,
                'weight' => 5.0,
                'user_id' => 3,
                'branch_id' => 2,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
            11 => 
            array (
                'id' => 27,
                'code' => 'WBS192060012',
                'number' => 'Pintu Forward',
                'description' => 'Pintu Forward',
                'deliverables' => 'Pintu Forward',
                'project_id' => 6,
                'wbs_id' => 24,
                'wbs_configuration_id' => 90,
                'status' => 1,
                'planned_duration' => 7,
                'planned_start_date' => date("Y-m-d",strtotime("+18 day", $date)),
                'planned_end_date' => date("Y-m-d",strtotime("+24 day", $date)),
                'actual_duration' => NULL,
                'actual_start_date' => NULL,
                'actual_end_date' => NULL,
                'progress' => 100.0,
                'weight' => 17.5,
                'user_id' => 3,
                'branch_id' => 2,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => date("Y-m-d",$date),
                'updated_at' => date("Y-m-d",$date),
            ),
        ));
        
    }
}